Repository genicam/harvesters, pull requests merged in 2022-03, with the labels that each got.

#290 Resolving #289
  src/harvesters/core.py
Labels: bug

#293 Some more updates on fix for issue 289
  src/harvesters/core.py
  src/harvesters/test/test_harvester_core.py
Labels: enhancement

#296 Have a remedy for custom payload types
  src/harvesters/core.py
Labels: enhancement

#299 Allow manually update the chunk data at any preferred timing
  src/harvesters/core.py
  src/harvesters/test/test_harvester_core.py
  src/harvesters/test/test_tutorials.py
Labels: enhancement

#302 Make node map exposed
  src/harvesters/core.py
  src/harvesters/test/test_harvester_core.py
Labels: enhancement

#303 Update the document arrangement
  INSTALL.rst
  README.rst
Labels: enhancement

#305 Drop the deprecated items
  src/harvesters/core.py
  src/harvesters/test/test_tutorials.py
Labels: enhancement, affects compatibility

#306 Do not expose debugging-purpose parameters
  src/harvesters/core.py
  src/harvesters/test/base_harvester.py
  src/harvesters/test/test_harvester_core.py
Labels: enhancement

#307 Announce the deprecation of the fetch_buffer method
  README.rst
  TUTORIAL.rst
  src/harvesters/core.py
  src/harvesters/test/test_harvester_core.py
  src/harvesters/test/test_tutorials.py
Labels: enhancement, affects compatibility

#308 Announce the deprecation of the start & stop_acquisition methods
  README.rst
  TUTORIAL.rst
  src/harvesters/core.py
  src/harvesters/test/test_acq_frame_rate.py
  src/harvesters/test/test_harvester_core.py
  src/harvesters/test/test_tutorials.py
Labels: enhancement, affects compatibility

#309 Do not expose num_filled_buffers_to_hold
  src/harvesters/core.py
Labels: enhancement, affects compatibility

#311 Rename run_in_background with run_as_thread
  src/harvesters/core.py
  src/harvesters/test/test_acq_frame_rate.py
  src/harvesters/test/test_harvester_core.py
Labels: enhancement

#313 Resolve issue #270
  src/harvesters/core.py
Labels: bug

#314 Remove unnecessary event notifications
  src/harvesters/core.py
Labels: bug

#315 Do not allow destroying multiple times
  src/harvesters/core.py
Labels: bug
